---
apiVersion: dashboard.opendatahub.io/v1alpha
kind: AcceleratorProfile
metadata:
  name: hpu-profile-first-gen-gaudi
  namespace: redhat-ods-applications
spec:
  displayName: Habana HPU - 1st Gen Gaudi
  description: First Generation Gaudi device
  enabled: true
  identifier: habana.ai/gaudi
  tolerations:
    - effect: NoSchedule
      key: habana.ai/gaudi
      operator: Exists
---
apiVersion: dashboard.opendatahub.io/v1alpha
kind: AcceleratorProfile
metadata:
  name: hpu-profile-gaudi
  namespace: redhat-ods-applications
spec:
  displayName: Habana HPU - 2nd Gen Gaudi
  description: Gaudi2 device
  enabled: true
  identifier: habana.ai/gaudi2
  tolerations:
    - effect: NoSchedule
      key: habana.ai/gaudi2
      operator: Exists
---
apiVersion: dashboard.opendatahub.io/v1alpha
kind: AcceleratorProfile
metadata:
  name: gpu-flex-series
  namespace: redhat-ods-applications
spec:
  displayName: Intel® Data Center GPU Flex Series
  description: Ideal for Model Serving purposes
  enabled: true
  identifier: intel.com/flex
  tolerations:
    - effect: NoSchedule
      key: intel.com/flex
      operator: Exists
---
apiVersion: dashboard.opendatahub.io/v1alpha
kind: AcceleratorProfile
metadata:
  name: gpu-max-series
  namespace: redhat-ods-applications
spec:
  displayName: Intel® Data Center GPU Max Series
  description: Ideal for Model Training purposes
  enabled: true
  identifier: intel.com/max
  tolerations:
    - effect: NoSchedule
      key: intel.com/max
      operator: Exists

