---
kind: List
metadata: {}
apiVersion: v1
items:
  -   apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
          name: redhat-ods-operator
  -   apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: rhods-catalog-dev
        namespace: redhat-ods-operator
      spec:
        displayName: Red Hat OpenShift Data Science
        publisher: RHODS Development Catalog
        # image: quay.io/modh/qe-catalog-source:latest
        # image: quay.io/lferrnan/odh-model-controller-container-live:1.33.0-habana
        # image: quay.io/lferrnan/rhods-operator-live-bundle:rhods-1.33.0-habana
        image: quay.io/lferrnan/rhods-operator-live-catalog:1.33.0-habana
        sourceType: grpc
  -   apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: rhods-operator-dev
        namespace: redhat-ods-operator
      spec:
        name: rhods-operator
        channel: beta
        source: rhods-catalog-dev
        sourceNamespace: redhat-ods-operator
  -   apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
          name: rhods-operator-dev
          namespace: redhat-ods-operator
